In [20]:
import numpy as np

In [21]:
var=np.genfromtxt(r"C:\Users\DELL\Downloads\tipsf.numpy.csv", delimiter=',', skip_header=1)
var

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [22]:
#1) What is the total bill value?
np.sum(var[:,1])

4827.77

In [27]:
#2) What is the total tip value? 
np.sum(var[:,2])

731.5799999999999

In [30]:
#3) Count how many times sun,sat,thu,fri are there?
z=np.unique(var[:,5],return_counts=True)
a,b=z
j=0
for i in a:
    if(i==0):
        print("sunday = ",b[j])
        j+=1
    elif(i==1):
        print("saturday = ",b[j])
        j+=1
    elif(i==2):
        print("thursday = ",b[j])
        j+=1
    elif(i==3):
        print("friday = ",b[j])
        j+=1   

sunday =  87
saturday =  76
thursday =  62
friday =  19


In [31]:
#4) How many smokers are there?
q=np.sum(var[:,4])
print(int(q),"smokers are there")

93 smokers are there


In [32]:
#5) What is the average tip given by female and male?
a=np.sum(var[:,2].take(np.where(var[:,3]==0)))
b=np.sum(var[:,2].take(np.where(var[:,3]==1)))
z=np.unique(var[:,3],return_counts=True)
q,w=z
print(a/w[0],"average tip given by female")
print(b/w[1],"average tip given by male")

2.8334482758620685 average tip given by female
3.0896178343949043 average tip given by male


In [33]:
#6) How much amount have been spent by female and male?
a=np.sum(var[:,1].take(np.where(var[:,3]==0)))
b=np.sum(var[:,1].take(np.where(var[:,3]==1)))
print("total amount spent by female: ",np.round(a))
print("total amount spent by male: ",np.round(b))

total amount spent by female:  1571.0
total amount spent by male:  3257.0


In [34]:
#7) What is the min and max tip given? 
max_tip=np.max(var[:,2])
min_tip=np.min(var[:,2])
print("maximum tip is ",max_tip)
print("minimum tip is ",min_tip)

maximum tip is  10.0
minimum tip is  1.0


In [41]:
#8) How many male and female are going for dinner and lunch?
n=np.unique(var[:,3].take(np.where((var[:,6]==1))),return_counts=True)      #(lunch)        
a,b=n
m=np.unique(var[:,3].take(np.where((var[:,6]==0))),return_counts=True)       #(dinner)
c,d=m
for y in a:
    if(y==0):
        print("total female going for lunch",b[0])
        print("total female going for dinner",d[0])
    else:
         print("total male going for lunch",b[1])
         print("total female going for dinner",d[1])

total female going for lunch 35
total female going for dinner 52
total male going for lunch 33
total female going for dinner 124


In [38]:
#9) Find out the average size?
n=np.unique(var[:,7],return_counts=True)
a,b=n
avg=np.sum(var[:,7])/np.sum(b)
print("average of size = ",np.round(avg))

average of size =  3.0


In [40]:
#10) Find how many female smokers and male smokers are there?
n=np.unique(var[:,3].take(np.where((var[:,4]==1))),return_counts=True)
a,b=n
for y in a:
    if(y==0):
        print("female smokers are : ",b[0])
    else:
        print("male smokers are : ",b[1])

female smokers are :  33
male smokers are :  60


In [25]:
var2=np.genfromtxt(r"C:\Users\DELL\Downloads\train_extended.csv", delimiter=",", skip_header=1)
var2

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [42]:
#1) What is the maximum and minnimum length?
n=np.max(var2[:,0])
print("print maximum length is ",n)
m=np.min(var2[:,0])
print("print minimum length is ",m)

print maximum length is  7.58349125
print minimum length is  0.0


In [44]:
#2) Find out the difference between max and min length?
def f(x):
    return np.max(x)-np.min(x)
np.apply_along_axis(f,0,var2[:,0])

array(7.58349125)

In [45]:
#3) Find column wise average?
def f1(x):
    return np.sum(x)/200000
np.apply_along_axis(f1,0,var2)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

In [46]:
#4) Find out all the age whose height is gereater than 0.4?
l=var2[:,7].take(np.where(var2[:,2]>0.4))
print(l.shape)
print(l)

(1, 55336)
[[11. 14. 13. ... 11. 11. 11.]]


In [47]:
#5) What is the average height and weight of the persons whose age is greater than 10?
height=var2[:,2].take(np.where(var2[:,7]>10))
count=height.shape
weight=var2[:,3].take(np.where(var2[:,7]>10))
count1=weight.shape
l1=list(count)
l2=list(count1)
print("average height is ",np.sum(height)/l1[1])
print("average weight is ",np.sum(weight)/l2[1])

average height is  0.4085813793498825
average weight is  31.681361864049048


In [49]:
#6) What is the shell weight?
np.round(np.sum(var2[:,6]))

1326846.0

In [50]:
#7) How many persons belongs to each and every unique age?
np.unique(var2[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [51]:
#8) What is the differemce between shucked weight and viscera weight?
n=np.sum(var2[:,4])
m=np.sum(var2[:,5])
print("the difference between shucked weight and viscera weight is ",np.round(n-m))

the difference between shucked weight and viscera weight is  999238.0


In [53]:
#9) What is the average height of the persons whose age is between 14 and 19?
n=var2.take(np.where((var2[:,7]>14) & (var2[:,7]<19)))
sum=np.sum(n)
count=list(n.shape)
print("the average height of the persons whose age is between 14 and 19 is ",np.round(sum/count[1]))

the average height of the persons whose age is between 14 and 19 is  7.0


In [54]:
#10) What is the average weight if we include all shucked weight ,viscera weight and shell weight with weight.
n=np.sum(var2[:,3:7])
count=list(var2.shape)
print("the average weight if we include all shucked weight ,viscera weight and shell weight with weight is ",np.round(n/count[0]))

the average weight if we include all shucked weight ,viscera weight and shell weight with weight is  45.0
