In [1]:
# Write a program to create a 5 dimensional array with all zeros and ones
import numpy as np
zero=np.zeros((1,1,1,5,4),dtype=int)

In [2]:
zero

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]]]])

In [3]:
one=np.ones((1,1,1,5,4),dtype=int)

In [4]:
one

array([[[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]]])

In [6]:
#Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)
n=[]
x=np.arange(1,31).reshape(3,10)
for y in x.flatten():
    if (y<=10):
        n.append(0)
    elif (11<=y<=20):
        n.append(1)
    else:
        n.append(5)
l=np.array(n).reshape(3,10)
print(l)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5 5]]


In [7]:
#Write a program to create a 3x4 matrix filled with values from 10 to 21.
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [11]:
#Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [12]:
#Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.
n=np.arange(1,17).reshape(4,4)
m=n[:,::-1]
print(n)
print()
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [13]:
#Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]
n=np.arange(12,28)
n[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [18]:
#Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100
n=np.arange(1,101).reshape(10,10)
m=(n>30) & (n<80) & (n%5==0)
n[m]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [22]:
#Write a program to create a 2D array with 1 on the border and 0 inside.
n=int(input("Enter no of rows: "))
m=int(input("Enter no of columns: "))
l=np.zeros((n,m),dtype=int)
for i in l:
    l[0:1,:]=1
    l[-1:,:]=1
    l[:,0:1]=1
    l[:,-1:]=1
print(l)

Enter no of rows: 6
Enter no of columns: 6
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [40]:
#Write a program to create a checkerboard pattern .Don't use default array function
#Checkerboard pattern:                                                   
#[[0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]                                                      
# [0 1 0 1 0 1 0 1]                                                      
# [1 0 1 0 1 0 1 0]]

In [28]:
#Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]
x=[]
n=np.array([10,20,40,60])
m=np.array([10,30,40,50])

for i in n:
    for j in m:
        if i==j:
            x.append(i)
print(x)

[10, 40]


In [30]:
# Write a program to create an array 2d array and then reshape into 1d array
l=[]
n=int(input("Enter the no of elements: "))
for i in range(n):
    num=int(input("Enter the elements: "))
    l.append(num)
m=len(l)
x=np.array(l,ndmin=2)
print(x)
print(x.reshape(m))

Enter the no of elements: 6
Enter the elements: 1
Enter the elements: 2
Enter the elements: 3
Enter the elements: 4
Enter the elements: 5
Enter the elements: 6
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]


In [39]:
#Write a user defined function for creating a 1 or 2d array from scratch without using array functions
l=[]
n=int(input("enter the range: "))
for i in range(n):
    num=input("enter the elements: ")
    l.append(num)
print(l)

enter the range: 4
enter the elements: 1,2,3,4
enter the elements: 5,6,7,8
enter the elements: 4,3,2,1
enter the elements: 8,7,6,5
['1,2,3,4', '5,6,7,8', '4,3,2,1', '8,7,6,5']
